version: '3.7'

# Define services
services:
  # Server service
  app-server:
    build:
      context: betPawa-wallet-server
      dockerfile: Dockerfile
    ports:
      - "9099:9099"
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/betPawa?createDatabaseIfNotExist=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: rovsen
      SPRING_DATASOURCE_PASSWORD: rovsen
    networks:
      - server
      - client

  # Client Service
  app-client:
    build:
      context: betPawa-wallet-client
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - app-server
    networks:
      - client

  # Database Service (Mysql)
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: betPawa
      MYSQL_USER: rovsen
      MYSQL_PASSWORD: rovsen
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - server

# Volumes
volumes:
  db-data:

# Networks
networks:
  server:
  client: