server:
  port: 8080
spring:
  application:
    name: betPawa-wallet-client

grpc:
  client:
    betPawa-wallet-server:
      host:
        - 127.0.0.1
      port:
        - 9090
      enableKeepAlive: true
      keepAliveWithoutCalls: true